library(corrplot)
spam_data <- read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data", header=FALSE)
spam_dataframe <- as.data.frame(spam_data)
M1 <- cor(spam_dataframe)
#corrplot(M1, method = "circle")
#corrplot(M1, method = "number")

maxs <-	apply(spam_dataframe,	MARGIN	=	2,	max)
mins <- apply(spam_dataframe, MARGIN=2,min)
instances <- sample(1:nrow(spam_data),size=0.8*nrow(spam_data))
scaled <- spam_dataframe
scaled =	 as.data.frame(scale(spam_dataframe,	center	=	TRUE,	scale	=	maxs	- mins))
M2 <- cor(scaled)
corrplot(M2, method = "circle")
corrplot(M2, method = "number")
